# Generated by Django 5.1.4 on 2025-01-04 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessosPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='pdfs/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('autor_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('reus', models.JSONField(blank=True, null=True)),
                ('reus_documentos', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='process_info', to='uploads.processospdf')),
            ],
        ),
    ]
