# Generated by Django 5.1.4 on 2025-01-04 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processinfo',
            name='pdf',
        ),
    ]
