# Generated by Django 5.1.4 on 2025-01-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0002_processinfo_numero_processo_processinfo_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processinfo",
            name="autor_documento",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="processinfo",
            name="autor_nome",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="processinfo",
            name="numero_processo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="processinfo",
            name="reus",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="processinfo",
            name="reus_documentos",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="processinfo",
            name="status",
            field=models.CharField(
                choices=[
                    ("Em Andamento", "Em Andamento"),
                    ("Finalizado", "Finalizado"),
                ],
                default="Em Andamento",
                max_length=30,
            ),
        ),
    ]
